services:
  search-node:
    build:
      context: ./knn-node
      dockerfile: src/main/docker/Dockerfile.jvm
    ports:
      - "48100:48100"
    environment:
      KNN_SINGLE_NODE: "true"
      KNN_INDEX_PATH: NONE
      KNN_DATA_DIR: /data
    volumes:
      - search-data:/data

volumes:
  search-data:
